version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "start:dev"]
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_NAME=master-portal-backend-dev
      - DATABASE_URL=mysql://root@db:3306/master_portal_backend_dev
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: master-portal-backend-dev
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
